### ISSUE TITLE
Specification for impellerC path

### ISSUE THREAD

**Issue by PistonShot1** [bdero/flutter-gpu-examples#1]
This not exactly an issue. I am having a problem to figuring out the path for IMPELLERC that is specified in the run.sh script.

`set -ex

SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)
ENGINE_DIR=~/Projects/engine
IMPELLERC=$ENGINE_DIR/impeller

mkdir -p $SCRIPT_DIR/assets
$IMPELLERC \
 ...`

is it referring to the impeller directory, of the engine directory i cloned ? because that is the one I default to at the moment and I dont think that was correct.

**Comment by bdero** [comment]
If you build Flutter Engine, then ImpellerC is located in the out directory. For example: `IMPELLERC=/path/to/engine/src/out/host_debug_unopt_arm64/impellerc`

But you can also use the ImpellerC binary that ships with the engine artifacts (downloaded by the Flutter tool). For example: `IMPELLERC=/path/to/flutter/bin/cache/artifacts/engine/darwin-x64/impellerc`

**Comment by hupptechnologies** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
iclosure, @10horizons, @psypersky, @fightudy, @degule, @SemiLavender, @silvawp, @giacuong171, @jiankan, @lyymoo, @joellobo, @Jofen, @JoeByte, @matthewjablack, @jezsmith720, @dntAtMe, @curto83, @Seubill, @tofudfy, @chemmist, @LiuYanrong, @outdamud, @ronindong, @Digi-Dev, @emsheets, @charlesYolee, @NewAeonDesign, @BinWu1989, @Laicure, @captainamin, @gaizka-allende, @H11C10, @vmelikyan, @singleside, @franci, @pdinkins, @assqingt, @jhonjoseph626, @exede-5801, @1834924958, @ft-awesome, @henryperson, @oslet, @cesarmiquel, @Beautifulone87, @mdslab87, @zhanfangjian, @MaxSikorski, @RunzhouLi, @mehmetcankerabuicke, @charlin90, @CloudSkyR, @duee, @ducthu, @aswanthkoleri, @sun0720, @Symars, @taawieta, @nikzaugg, @codehz, @lazyanubis, @m-manu, @edzhangsy, @yinnxinn, @MaxiIT, @Numberartificial, @hnoye, @OSSpinLock, @huazhouji, @drewroberts, @KoterRomanov, @zeroearl, @AhmedSaeidMakki, @rodoufu, @PLJean, @webopbro4, @wangcser, @d6n13l0l1v3r, @zhanfangjian, @BlockHackTk, @lee4755026, @codex8089, @justicelee, @EverythingSalesforce, @Johnlee666, @Wangdi, @brunneus, @LiuYanrong, @joshkmartinez, @unbanksytv, @jmcdl, @JoeByte, @mikeulicny, @ablack13, @JulienGuo, @thomaspham12345, @lexuansang93, @chapche, @ronghuang0

**Comment by munrocket** [comment]
@bdero is there a way how to use custom renderer? 

Impeller and flutter-scene is good but we want opportunity to add custom ffi engines in C/C++ with own GAPI wrapper for games. Is there a way how to use flutter is only for UI or as a platform wrapper?

**Comment by bdero** [comment]
Flutter can interface with external renderers via [native platform views](https://docs.flutter.dev/platform-integration/ios/platform-views) or [custom embedders](https://docs.flutter.dev/embedded).

But for Flutter GPU, symbols rely on passing Dart objects back and forth. So it's not really possible to use it without Dart.
